version: "3"
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"